### ISSUE TITLE
locking2

### ISSUE THREAD

**Issue by pithyless** [borkdude/dynaload#1]
Reading the source, I was curious why `locking2` exists (vs. say `clojure.core/locking`) and went down the rabbit hole.

Perhaps it would be beneficial to add a comment and point others to [CLJ-1472](https://clojure.atlassian.net/browse/CLJ-1472)? This looks like it will be fixed upstream in Clojure 1.10.2.

**Comment by borkdude** [comment]
PR welcome. That macro indeed takes care of an issue with GraalVM for older Clojure versions.

**Comment by borkdude** [comment]
Btw, `locking2` comes directly from clojure.spec.alpha so it's been already explain in the sense that all code in this library is directly extracted mostly as is from spec.
