### ISSUE TITLE
Dynaload without throwing exceptions

### ISSUE THREAD

**Issue by ikitommi** [borkdude/dynaload#4]
In my use case, I would just like to check if the Var can be loaded and use a client defined fallback logic if it's not. Currently, the api only throws. I could catch the exception, but would be great to have a non-throwing variant (via options map? a new fn/macro?) that would just return `nil` if the Var is not present.

**Comment by borkdude** [comment]
@ikitommi I now added an optional options map that supports `:default` - would be great if you could try this out before I document this as officially supported.

**Comment by borkdude** [comment]
Also added unit tests now.

**Comment by ikitommi** [comment]
looks great, a small improvement in #5
